name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v7
      with:
        node-version-file: .nvmrc
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm
    - name: Build
      run: pnpm install --frozen-lockfile && pnpm run build
    - run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
